name: bookingapp
description: booking application for algoriza  made with flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.2.1
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  provider: ^6.0.3
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Peter
      fonts:
        - asset: assets/fonts/Peter-regular.otf
        - asset: assets/fonts/Peter-black.otf
          weight: 700

    - family: Work_Sans
      fonts:
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
