name: bookingapp
description: booking application for algoriza  made with flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  internet_connection_checker: ^0.0.1+4
  get_it: ^7.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  #assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  #fonts:
  #  - family: Schyler
  #    fonts:
  #      - asset: fonts/Schyler-Regular.ttf
  #      - asset: fonts/Schyler-Italic.ttf
  #        style: italic
  #  - family: Trajan Pro
  #    fonts:
  #      - asset: fonts/TrajanPro.ttf
  #      - asset: fonts/TrajanPro_Bold.ttf
  #        weight: 700
