import 'package:bookingapp/src/core/utils/asset_manager.dart';
import 'package:bookingapp/src/features/search_explore/domain/entities/room_data.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';


class HotelListData {
  String imagePath;
  String titleTxt;
  String subTxt;
  DateText? date;
  String dateTxt;
  String roomSizeTxt;
  RoomData? roomData;
  double dist;
  double rating;
  int reviews;
  int perNight;
  bool isSelected;
  PeopleSleeps? peopleSleeps;
  LatLng? location;
  Offset? screenMapPin; // we used this screen Offset for adding on Map layer

  HotelListData({
    this.imagePath = '',
    this.titleTxt = '',
    this.subTxt = "",
    this.dateTxt = "",
    this.roomSizeTxt = "",
    this.roomData,
    this.dist = 1.8,
    this.reviews = 80,
    this.rating = 4.5,
    this.perNight = 180,
    this.isSelected = false,
    this.date,
    this.peopleSleeps,
    this.location,
    this.screenMapPin,
  });

  // we need location in this hotelList bcz we using that in map
  static List<HotelListData> hotelList = [
    HotelListData(
      imagePath: ImageAssets.hotel_1,
      titleTxt: 'Palm Inn Hotel',
      subTxt: 'Hurghada, Egypt',
      dist: 2.0,
      reviews: 80,
      rating: 8.0,
      perNight: 38,
      roomData: RoomData(1, 2),
      isSelected: true,
      date: DateText(1, 5),
      location: const LatLng(27.259102, 33.812999),
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_2,
      titleTxt: 'Albatros Aqua Park Resort - By Pickalbatros',
      subTxt: 'Hurghada, Egypt',
      dist: 4.0,
      reviews: 74,
      rating: 8.9,
      perNight: 120,
      roomData: RoomData(1, 3),
      isSelected: false,
      date: DateText(2, 6),
      location: const LatLng(27.135312, 33.8116368),
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_3,
      titleTxt: 'Elite Suites Hurghada',
      subTxt: 'Hurghada, Egypt',
      dist: 3.0,
      reviews: 62,
      rating: 9.2,
      perNight: 50,
      roomData: RoomData(2, 3),
      isSelected: false,
      date: DateText(5, 9),
      location: const LatLng(27.150182, 33.826711),
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_4,
      titleTxt: 'Pyramisa Beach Resort Sahl Hasheesh',
      subTxt: 'Hurghada, Egypt',
      dist: 7.0,
      reviews: 90,
      rating: 7.5,
      perNight: 50,
      isSelected: false,
      roomData: RoomData(2, 2),
      date: DateText(1, 5),
      location: const LatLng(27.049302, 33.900214),
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_5,
      titleTxt: 'Pyramisa Beach',
      subTxt: 'Hurghada, Egypt',
      dist: 2.0,
      reviews: 240,
      rating: 7.5,
      isSelected: false,
      perNight: 50,
      roomData: RoomData(1, 7),
      date: DateText(1, 4),
      location: const LatLng(27.049302, 33.900214),
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_1,
      titleTxt: 'Pyramisa Beach 2',
      subTxt: 'Hurghada, Egypt',
      dist: 2.0,
      reviews: 80,
      rating: 7.5,
      perNight: 50,
      roomData: RoomData(1, 2),
      isSelected: true,
      date: DateText(1, 5),
      location: const LatLng(27.049302, 33.900214),
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_2,
      titleTxt: 'Pyramisa Beach 3',
      subTxt: 'Hurghada, Egypt',
      dist: 4.0,
      reviews: 74,
      rating: 7.5,
      perNight: 50,
      roomData: RoomData(1, 3),
      isSelected: false,
      date: DateText(2, 6),
      location: const LatLng(27.049302, 33.900214),
    ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_3,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 3.0,
    //   reviews: 62,
    //   rating: 4.0,
    //   perNight: 60,
    //   roomData: RoomData(2, 3),
    //   isSelected: false,
    //   date: DateText(5, 9),
    //   location: const LatLng(51.499162, -0.119788),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_4,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 7.0,
    //   reviews: 90,
    //   rating: 4.4,
    //   perNight: 170,
    //   isSelected: false,
    //   roomData: RoomData(2, 2),
    //   date: DateText(1, 5),
    //   location: const LatLng(51.519541, -0.114503),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_5,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 240,
    //   rating: 4.5,
    //   isSelected: false,
    //   perNight: 200,
    //   roomData: RoomData(1, 7),
    //   date: DateText(1, 4),
    //   location: const LatLng(51.508383, -0.109502),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_1,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 80,
    //   rating: 4.4,
    //   perNight: 180,
    //   roomData: RoomData(1, 2),
    //   isSelected: true,
    //   date: DateText(1, 5),
    //   location: const LatLng(51.516898, -0.143377),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_2,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 4.0,
    //   reviews: 74,
    //   rating: 4.5,
    //   perNight: 200,
    //   roomData: RoomData(1, 3),
    //   isSelected: false,
    //   date: DateText(2, 6),
    //   location: const LatLng(51.505799, -0.137904),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_3,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 3.0,
    //   reviews: 62,
    //   rating: 4.0,
    //   perNight: 60,
    //   roomData: RoomData(2, 3),
    //   isSelected: false,
    //   date: DateText(5, 9),
    //   location: const LatLng(51.499162, -0.119788),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_4,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 7.0,
    //   reviews: 90,
    //   rating: 4.4,
    //   perNight: 170,
    //   isSelected: false,
    //   roomData: RoomData(2, 2),
    //   date: DateText(1, 5),
    //   location: const LatLng(51.519541, -0.114503),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_5,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 240,
    //   rating: 4.5,
    //   isSelected: false,
    //   perNight: 200,
    //   roomData: RoomData(1, 7),
    //   date: DateText(1, 4),
    //   location: const LatLng(51.508383, -0.109502),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_1,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 80,
    //   rating: 4.4,
    //   perNight: 180,
    //   roomData: RoomData(1, 2),
    //   isSelected: true,
    //   date: DateText(1, 5),
    //   location: const LatLng(51.516898, -0.143377),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_2,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 4.0,
    //   reviews: 74,
    //   rating: 4.5,
    //   perNight: 200,
    //   roomData: RoomData(1, 3),
    //   isSelected: false,
    //   date: DateText(2, 6),
    //   location: const LatLng(51.505799, -0.137904),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_3,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 3.0,
    //   reviews: 62,
    //   rating: 4.0,
    //   perNight: 60,
    //   roomData: RoomData(2, 3),
    //   isSelected: false,
    //   date: DateText(5, 9),
    //   location: const LatLng(51.499162, -0.119788),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_4,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 7.0,
    //   reviews: 90,
    //   rating: 4.4,
    //   perNight: 170,
    //   isSelected: false,
    //   roomData: RoomData(2, 2),
    //   date: DateText(1, 5),
    //   location: const LatLng(51.519541, -0.114503),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_5,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 240,
    //   rating: 4.5,
    //   isSelected: false,
    //   perNight: 200,
    //   roomData: RoomData(1, 7),
    //   date: DateText(1, 4),
    //   location: const LatLng(51.508383, -0.109502),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_1,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 80,
    //   rating: 4.4,
    //   perNight: 180,
    //   roomData: RoomData(1, 2),
    //   isSelected: true,
    //   date: DateText(1, 5),
    //   location: const LatLng(51.516898, -0.143377),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_2,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 4.0,
    //   reviews: 74,
    //   rating: 4.5,
    //   perNight: 200,
    //   roomData: RoomData(1, 3),
    //   isSelected: false,
    //   date: DateText(2, 6),
    //   location: const LatLng(51.505799, -0.137904),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_3,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 3.0,
    //   reviews: 62,
    //   rating: 4.0,
    //   perNight: 60,
    //   roomData: RoomData(2, 3),
    //   isSelected: false,
    //   date: DateText(5, 9),
    //   location: const LatLng(51.499162, -0.119788),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_4,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 7.0,
    //   reviews: 90,
    //   rating: 4.4,
    //   perNight: 170,
    //   isSelected: false,
    //   roomData: RoomData(2, 2),
    //   date: DateText(1, 5),
    //   location: const LatLng(51.519541, -0.114503),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_5,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 240,
    //   rating: 4.5,
    //   isSelected: false,
    //   perNight: 200,
    //   roomData: RoomData(1, 7),
    //   date: DateText(1, 4),
    //   location: const LatLng(51.508383, -0.109502),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_1,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 80,
    //   rating: 4.4,
    //   perNight: 180,
    //   roomData: RoomData(1, 2),
    //   isSelected: true,
    //   date: DateText(1, 5),
    //   location: const LatLng(51.516898, -0.143377),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_2,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 4.0,
    //   reviews: 74,
    //   rating: 4.5,
    //   perNight: 200,
    //   roomData: RoomData(1, 3),
    //   isSelected: false,
    //   date: DateText(2, 6),
    //   location: const LatLng(51.505799, -0.137904),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_3,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 3.0,
    //   reviews: 62,
    //   rating: 4.0,
    //   perNight: 60,
    //   roomData: RoomData(2, 3),
    //   isSelected: false,
    //   date: DateText(5, 9),
    //   location: const LatLng(51.499162, -0.119788),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_4,
    //   titleTxt: 'Queen Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 7.0,
    //   reviews: 90,
    //   rating: 4.4,
    //   perNight: 170,
    //   isSelected: false,
    //   roomData: RoomData(2, 2),
    //   date: DateText(1, 5),
    //   location: const LatLng(51.519541, -0.114503),
    // ),
    // HotelListData(
    //   imagePath: ImageAssets.hotel_5,
    //   titleTxt: 'Grand Royal Hotel',
    //   subTxt: 'Wembley, London',
    //   dist: 2.0,
    //   reviews: 240,
    //   rating: 4.5,
    //   isSelected: false,
    //   perNight: 200,
    //   roomData: RoomData(1, 7),
    //   date: DateText(1, 4),
    //   location: const LatLng(51.508383, -0.109502),
    // ),
  ];

  static List<HotelListData> popularList = [
    HotelListData(
      imagePath: ImageAssets.popular_1,
      titleTxt: 'Paris',
    ),
    HotelListData(
      imagePath: ImageAssets.popular_2,
      titleTxt: 'Spain',
    ),
    HotelListData(
      imagePath: ImageAssets.popular_3,
      titleTxt: 'Vernazza',
    ),
    HotelListData(
      imagePath: ImageAssets.popular_4,
      titleTxt: 'London',
    ),
    HotelListData(
      imagePath: ImageAssets.popular_5,
      titleTxt: 'Venice',
    ),
    HotelListData(
      imagePath: ImageAssets.popular_6,
      titleTxt: 'Diamond Head',
    ),
  ];

  static List<HotelListData> reviewsList = [
    HotelListData(
      imagePath: ImageAssets.avatar1,
      titleTxt: 'Alexia Jane',
      subTxt:
          'This is located in a great spot close to shops and bars, very quiet location',
      rating: 8.0,
      dateTxt: '21 May, 2019',
    ),
    HotelListData(
      imagePath: ImageAssets.avatar3,
      titleTxt: 'Jacky Depp',
      subTxt:
          'Good staff, very comfortable bed, very quiet location, place could do with an update',
      rating: 8.0,
      dateTxt: '21 May, 2019',
    ),
    HotelListData(
      imagePath: ImageAssets.avatar5,
      titleTxt: 'Alex Carl',
      subTxt:
          'This is located in a great spot close to shops and bars, very quiet location',
      rating: 6.0,
      dateTxt: '21 May, 2019',
    ),
    HotelListData(
      imagePath: ImageAssets.avatar2,
      titleTxt: 'May June',
      subTxt:
          'Good staff, very comfortable bed, very quiet location, place could do with an update',
      rating: 9.0,
      dateTxt: '21 May, 2019',
    ),
    HotelListData(
      imagePath: ImageAssets.avatar4,
      titleTxt: 'Lesley Rivas',
      subTxt:
          'This is located in a great spot close to shops and bars, very quiet location',
      rating: 8.0,
      dateTxt: '21 May, 2019',
    ),
    HotelListData(
      imagePath: ImageAssets.avatar6,
      titleTxt: 'Carlos Lasmar',
      subTxt:
          'Good staff, very comfortable bed, very quiet location, place could do with an update',
      rating: 7.0,
      dateTxt: '21 May, 2019',
    ),
    HotelListData(
      imagePath: ImageAssets.avatar7,
      titleTxt: 'Oliver Smith',
      subTxt:
          'This is located in a great spot close to shops and bars, very quiet location',
      rating: 9.0,
      dateTxt: '21 May, 2019',
    ),
  ];

  static List<HotelListData> romeList = [
    HotelListData(
        imagePath:
            'assets/images/room_1.jpg assets/images/room_2.jpg assets/images/room_3.jpg',
        titleTxt: 'Deluxe Room',
        perNight: 180,
        dateTxt: 'Sleeps 3 people',
        roomData: RoomData(2, 2)),
    HotelListData(
        imagePath:
            'assets/images/room_4.jpg assets/images/room_5.jpg assets/images/room_6.jpg',
        titleTxt: 'Premium Room',
        perNight: 200,
        dateTxt: 'Sleeps 3 people + 2 children',
        roomData: RoomData(3, 2)),
    HotelListData(
        imagePath:
            'assets/images/room_7.jpg assets/images/room_8.jpg assets/images/room_9.jpg',
        titleTxt: 'Queen Room',
        perNight: 240,
        dateTxt: 'Sleeps 4 people + 4 children',
        roomData: RoomData(4, 4)),
    HotelListData(
        imagePath:
            'assets/images/room_10.jpg assets/images/room_11.jpg assets/images/room_12.jpg',
        titleTxt: 'King Room',
        perNight: 240,
        dateTxt: 'Sleeps 4 people + 4 children',
        roomData: RoomData(4, 4)),
    HotelListData(
        imagePath:
            'assets/images/room_11.jpg assets/images/room_1.jpg assets/images/room_2.jpg',
        titleTxt: 'Hollywood Twin\nRoom',
        perNight: 260,
        dateTxt: 'Sleeps 4 people + 4 children',
        roomData: RoomData(4, 4)),
  ];

  static List<HotelListData> hotelTypeList = [
    HotelListData(
      imagePath: ImageAssets.hotel_Type_1,
      titleTxt: 'hotel_data',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_2,
      titleTxt: 'Backpacker_data',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_3,
      titleTxt: 'Resort_data',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_4,
      titleTxt: 'villa_data',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_5,
      titleTxt: 'apartment',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_6,
      titleTxt: 'guest_house',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_7,
      titleTxt: 'motel',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_8,
      titleTxt: 'accommodation',
      isSelected: false,
    ),
    HotelListData(
      imagePath: ImageAssets.hotel_Type_9,
      titleTxt: 'Bed_breakfast',
      isSelected: false,
    ),
  ];
  static List<HotelListData> lastsSearchesList = [
    HotelListData(
      imagePath: ImageAssets.popular_4,
      titleTxt: 'London',
      roomData: RoomData(1, 3),
      date: DateText(12, 22),
      dateTxt: '12 - 22 Dec',
    ),
    HotelListData(
      imagePath: ImageAssets.popular_1,
      titleTxt: 'Paris',
      roomData: RoomData(1, 3),
      date: DateText(12, 24),
      dateTxt: '12 - 24 Sep',
    ),
    HotelListData(
      imagePath: ImageAssets.city_3,
      titleTxt: 'New York',
      roomData: RoomData(1, 3),
      date: DateText(20, 22),
      dateTxt: '20 - 22 Sep',
    ),
    HotelListData(
      imagePath: ImageAssets.city_4,
      titleTxt: 'Tokyo',
      roomData: RoomData(12, 22),
      date: DateText(12, 22),
      dateTxt: '12 - 22 Nov',
    ),
    HotelListData(
      imagePath: ImageAssets.city_5,
      titleTxt: 'Shanghai',
      roomData: RoomData(10, 15),
      date: DateText(10, 15),
      dateTxt: '10 - 15 Dec',
    ),
    HotelListData(
      imagePath: ImageAssets.city_6,
      titleTxt: 'Moscow',
      roomData: RoomData(12, 14),
      date: DateText(12, 14),
      dateTxt: '12 - 14 Dec',
    ),
  ];
}
